services:
  app:
    build: .
    container_name: go_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./.env:/usr/local/app/.env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${NAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DBNAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
